apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-landing
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AI Tutor</title>
        <style>
            body {
                margin: 0;
                padding: 0;
                font-family: 'Arial', sans-serif;
                background: linear-gradient(to right, #6a11cb, #2575fc);
                color: white;
                text-align: center;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                height: 100vh;
            }
            h1 {
                font-size: 2.5em;
                font-weight: bold;
                margin-bottom: 20px;
            }
            p {
                font-size: 1.2em;
                max-width: 600px;
                line-height: 1.6;
            }
            .cta-button {
                display: inline-block;
                margin-top: 20px;
                padding: 12px 24px;
                font-size: 1.2em;
                color: white;
                background-color: #ff4081;
                border: none;
                border-radius: 8px;
                text-decoration: none;
                transition: 0.3s;
            }
            .cta-button:hover {
                background-color: #e73370;
            }
        </style>
    </head>
    <body>
        <h1>AI Tutor will change the world's education system!</h1>
        <p>Experience the future of learning with AI-driven personalized education. Start your journey today!</p>
        <a href="#" class="cta-button">Get Started</a>
    </body>
    </html>

  nginx.conf: |
    user nginx;
    worker_processes auto;
    
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;
    
    events {
      worker_connections 1024;
    }
    
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      
      access_log /var/log/nginx/access.log main;
      
      sendfile on;
      keepalive_timeout 65;
      
      server {
        listen 80;
        server_name aitutor.today www.aitutor.today;
        
        location / {
          root /usr/share/nginx/html;
          index index.html;
          try_files $uri $uri/ =404;
        }
      }
    }